export * from "./home";
export * from "./login";
export * from "./dashboard";
export * from "./error";
export * from "./test";
export * from "./course/vod";
export * from "./member/index"
export * from "./member/create"
export * from "./member/update"
export * from "./system/administrator/index"
export * from "./system/administrator/create"
export * from "./system/administrator/update"
